# Poimandres Storm.
background = #2d333e
foreground = #ffffff
bold-color = #ffffff
selection-background = #404350
selection-foreground = #ffffff
cursor-color = #607487
cursor-text = #ffffff
palette = 0=#1b1e28
palette = 1=#ffb473
palette = 2=#8cd298
palette = 3=#fffac2
palette = 4=#96b2ea
palette = 5=#cba6f7
palette = 6=#96b2ea
palette = 7=#ffffff
palette = 8=#a6accd
palette = 9=#ffb473
palette = 10=#8cd298
palette = 11=#fffac2
palette = 12=#add7ff
palette = 13=#cba6f7
palette = 14=#add7ff
palette = 15=#ffffff
