# Poimandres Storm.

# Pane borders
set -g pane-border-style "fg=#33394a"
set -g pane-active-border-style "fg=#5de4c7"

# Agent indicator
set -g @agent-indicator-running-border '#96b2ea'
set -g @agent-indicator-running-window-title-bg '#96b2ea'
set -g @agent-indicator-running-window-title-fg '#252b37,bold'
set -g @agent-indicator-needs-input-border '#ffb473'
set -g @agent-indicator-needs-input-window-title-bg '#ffb473'
set -g @agent-indicator-needs-input-window-title-fg '#252b37,bold'
set -g @agent-indicator-done-border '#cba6f7'
set -g @agent-indicator-done-window-title-bg '#cba6f7'
set -g @agent-indicator-done-window-title-fg '#252b37,bold'
